import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Layout from '../components/layout'
import {TOKEN,DATABASE_ID} from "../config";
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home(data) {
  return (

    
    <Layout>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.6.0/p5.js"></script>
      <Head>
        <title>Coding Effects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <h1>Coding Effects is a creative coding learning platform</h1>

    </Layout>
  )
}